on: push

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: terraform/env/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - run: |
          cd terraform
          pwd
          ls -la
